### ISSUE TITLE
ffmpeg

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [lynxlynx/tfcrypt#3]
Hi,
how can I use tfcrypt with ffmpeg in command line / real time?
possible?

thanks

**Comment by strlcat** [comment]
Depends on what you want.

If you want just to encrypt the output of ffmpeg, then you have to force ffmpeg to spit data to stdout. Then doing a simple pipe of `| tfcrypt -e theKey.bin - encrypted.mp4` will do the trick.

If you want to encrypt the raw content of any encoded stream, so it would appear in player like a white noise, then I cannot give you much help there because I am not in any way an ffmpeg enthusiast. You have to dig the correct ffmpeg command line to take the random data and split/encode it into separate video and audio streams "as is", just to see how white noise looks like. It would be more interesting to encode some ECB encrypted data this way and see how redundant encrypted data looks like.

What else I may missed? Don't know. You probably need first option, since you did not provided more information to think about.

Sorry, I have to close this issue since it is much more a question which you should send me by email. There is no problem with tfcrypt itself.
